name: ciao_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fab_circular_menu: ^1.0.0
  line_icons: ^0.2.0
  introduction_screen: ^1.0.7
  flutter_svg: ^0.17.4
  intl: ^0.16.1
  sqflite: ^1.3.0
  path_provider: ^1.6.11
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  app_settings: 4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner:

flutter:

  uses-material-design: true

  fonts:
    - family: BungeeInLine
      fonts:
        - asset: assets/fonts/BungeeInLine-Regular.ttf
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg




