name: ciao_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"
  cupertino_icons: ^0.1.2
  fab_circular_menu: ^1.0.0
  flutter_svg: ^0.17.4
  intl: ^0.16.1
  path_provider: ^1.6.11
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  app_settings: ^4.0.4
  carousel_slider: ^2.3.1
  animate_icons: ^1.0.0
  flushbar: ^1.10.4
  introduction_screen: ^1.0.7
  flutter_native_timezone: ^1.0.4
  flutter_local_notifications: ^3.0.2
  table_calendar: ^2.3.3
  animations: ^1.1.2
  flutter_slidable: ^0.5.7
  dynamic_overflow_menu_bar: ^0.1.2
  responsive_framework: ^0.0.14
  vibration: ^1.7.3
  awesome_dialog: ^1.3.1
  shared_preferences: '<2.0.0'
  provider: ^4.3.2+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/textures/

  fonts:
    - family: BungeeInLine
      fonts:
        - asset: assets/fonts/BungeeInLine-Regular.ttf
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: FrauncesThin
      fonts:
        - asset: assets/fonts/FrauncesThin.ttf    
    - family: FrauncesBoldItalic
      fonts:
        - asset: assets/fonts/FrauncesBoldItalic.ttf
    - family: FrauncesBold
      fonts:
        - asset: assets/fonts/FrauncesBold.ttf     
    - family: RighteousRegular
      fonts:
        - asset: assets/fonts/RighteousRegular.ttf   
         
    - family: FrauncesRegular
      fonts:
        - asset: assets/fonts/FrauncesRegular.ttf   
         
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf  

    - family: DMSerifTextRegular 
      fonts:
        - asset: assets/fonts/DMSerifTextRegular.ttf                

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
