name: ciao_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  fab_circular_menu: ^1.0.0
  line_icons: ^0.2.0
  introduction_screen: ^1.0.7
  flutter_svg: ^0.17.4
  lite_rolling_switch: ^0.1.1
  toggle_switch: ^0.1.4
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  sqflite: ^1.3.0
  path_provider: ^1.6.11
  hive: ^1.4.4
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner:

flutter:
  assets:
    - images/red.png
    - images/userIcon.png
    - images/intro1.svg
    - images/intro2.svg
    - images/intro3.svg
    - images/intro4.svg


  uses-material-design: true

  fonts:
    - family: BungeeInLine
      fonts:
        - asset: assets/fonts/BungeeInLine-Regular.ttf
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family:  FireAppIcon
      fonts:
        - asset: assets/fonts/FireAppIcon.ttf
    - family:  AddTaskIcon
      fonts:
        - asset: assets/fonts/AddTaskIcon.ttf

    - family:  MenuBarIcon
      fonts:
        - asset: assets/fonts/MenuBarIcon.ttf
    - family:  RateMenuIcon
      fonts:
        - asset: assets/fonts/RateMenuIcon.ttf
    - family:  AboutMenuIcon
      fonts:
        - asset: assets/fonts/AboutMenuIcon.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg




