/// Flutter icons AddTaskIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AddTaskIcon
///      fonts:
///       - asset: fonts/AddTaskIcon.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class AddTaskIcon {
  AddTaskIcon._();

  static const _kFontFam = 'AddTaskIcon';
  static const _kFontPkg = null;

  static const IconData highlight = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
